/**
 * Report Renderer
 * Main renderer for generating print reports
 * Supports multiple units: HDPE, PP, PPC
 * Supports template-based control print
 */

import { renderHeader, renderProductTitle } from './components/HeaderSection.js';
import { renderProductInfo, renderSpecifications } from './components/ProductInfo.js';
import { renderLogoSection } from './components/LogoSection.js';
import { validateReportData } from './utils/DataFormatter.js';
import { generatePrintHTML, openPrintPreview } from './utils/PrintHelper.js';
import { getUnitConfig } from './config/UnitConfig.js';
import { normalizeControlPrint, isFeatureEnabled } from './config/ReportConfig.js';
import { getTemplateById } from './config/TemplateConfig.js';

/**
 * Report Renderer Class
 */
export class ReportRenderer {
    constructor(data) {
        this.data = data;
        this.unit = data.unit || 'HDPE';
        this.unitConfig = getUnitConfig(this.unit);
        
        // NEW: Support template-based system
        if (data.template) {
            // Template format: {template: "template1/2/3", controlprint: {ft, lt}}
            this.template = data.template;
            this.controlprint = data.controlprint || { ft: false, lt: false };
            
            // Set flags for logo rendering
            this.showTIS = (data.template === 'template2' || data.template === 'template3');
            this.showQR = (data.template === 'template2' || data.template === 'template3');
            this.showSIRIM = (data.template === 'template3' && this.unit === 'HDPE');
            this.showFT = this.controlprint.ft;
            this.showLT = this.controlprint.lt;
            
            console.log(`📄 ReportRenderer (Template Mode): template=${this.template}, unit=${this.unit}, TIS=${this.showTIS}, SIRIM=${this.showSIRIM}, FT=${this.showFT}, LT=${this.showLT}`);
        } else {
            // Legacy: Binary controlPrint (backward compatibility)
            const controlPrint = normalizeControlPrint(data.controlPrint || 0);
            this.showTIS = isFeatureEnabled(controlPrint, 'TIS');
            this.showQR = this.showTIS;
            this.showSIRIM = isFeatureEnabled(controlPrint, 'SIRIM');
            this.showFT = isFeatureEnabled(controlPrint, 'FT');
            this.showLT = isFeatureEnabled(controlPrint, 'LT');
            
            console.log(`📄 ReportRenderer (Legacy Mode): controlPrint=${controlPrint}`);
        }
    }
    
    /**
     * Validate report data
     * @returns {Object} Validation result
     */
    validate() {
        return validateReportData(this.data);
    }
    
    /**
     * Render complete report HTML
     * @returns {string} Complete HTML document
     */
    render() {
        const validation = this.validate();
        
        if (!validation.valid) {
            console.error('Validation errors:', validation.errors);
            throw new Error(`Invalid report data: ${validation.errors.join(', ')}`);
        }
        
        const bodyContent = this.renderBody();
        const styles = this.getStyles();
        
        return generatePrintHTML(bodyContent, styles);
    }
    
    /**
     * Render report body content
     * @returns {string} HTML body content
     */
    renderBody() {
        return `
<div class="report-container" style="max-width: 800px; margin: 0 auto; background: white; padding: 20px;">
    ${renderHeader(this.data)}
    ${renderProductTitle(this.data)}
    ${renderProductInfo(this.data)}
    ${this.renderCustomContent()}
    ${renderLogoSection(this.data, this)}
    ${this.renderFTLTMarkers()}
    ${this.renderFooter()}
</div>`;
    }
    
    /**
     * Render FT/LT markers
     * @returns {string} HTML string
     */
    renderFTLTMarkers() {
        const ftHtml = this.showFT ? `<div style="position: absolute; right: 180px; top: 340px;"><p style="font-size: 50px;">(F/T)</p></div>` : '';
        const ltHtml = this.showLT ? `<div style="position: absolute; right: 180px; top: 495px;"><p style="font-size: 50px;">(L/T)</p></div>` : '';
        
        if (!ftHtml && !ltHtml) return '';
        
        return `
<div class="ft-lt-markers" style="position: relative;">
    ${ftHtml}
    ${ltHtml}
</div>`;
    }
    
    /**
     * Render custom content (can be overridden by unit-specific renderers)
     * @returns {string} HTML string
     */
    renderCustomContent() {
        const specs = this.unitConfig.defaultSpecs;
        return renderSpecifications(specs);
    }
    
    /**
     * Render footer section
     * @returns {string} HTML string
     */
    renderFooter() {
        return `
<div class="report-footer" style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; font-size: 12px; color: #888;">
    <p>Generated by HDPE Print Tag Jumbo System</p>
    <p>Date: ${new Date().toLocaleString('th-TH')}</p>
</div>`;
    }
    
    /**
     * Get custom styles for report
     * @returns {string} CSS string
     */
    getStyles() {
        return `
        body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 0;
            padding: 20px;
            background: #f5f5f5;
        }
        
        .report-container {
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        
        @media print {
            body {
                background: white;
                padding: 0;
            }
            
            .report-container {
                box-shadow: none;
                max-width: 100%;
            }
        }
        `;
    }
    
    /**
     * Preview report in new window
     */
    preview() {
        const html = this.render();
        openPrintPreview(html, `${this.unit} Report - ${this.data.grade || 'Preview'}`);
    }
    
    /**
     * Print report directly
     */
    print() {
        const html = this.render();
        const printWindow = window.open('', '_blank');
        
        if (!printWindow) {
            alert('Please allow popups for this site to print');
            return;
        }
        
        printWindow.document.write(html);
        printWindow.document.close();
        
        printWindow.onload = function() {
            printWindow.print();
        };
    }
}

/**
 * Create report renderer instance
 * @param {Object} data - Report data
 * @returns {ReportRenderer} Renderer instance
 */
export function createReportRenderer(data) {
    return new ReportRenderer(data);
}

/**
 * Quick render and preview
 * @param {Object} data - Report data
 */
export function renderAndPreview(data) {
    const renderer = createReportRenderer(data);
    renderer.preview();
}

/**
 * Quick render and print
 * @param {Object} data - Report data
 */
export function renderAndPrint(data) {
    const renderer = createReportRenderer(data);
    renderer.print();
}
